name: DOX CLI - Helm Release

on:
  workflow_dispatch:

jobs:
  package-base-helm-chart:
    runs-on: dox-runner-set
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: dox-cli helm release
        run: |
          dox helm template package push